### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by okkez**
Merge this PR after #32

### CODE REVIEW

**Comment by okkez** [comment]
CI failed but this will pass after merge #32.

**Comment by okkez** [comment]
@repeatedly How about this PR?

**Comment by repeatedly** [comment]
Just merged #32. Could you rebase the patch?

**Comment by repeatedly** [comment]
Ah, rebase seems not needed.

**Comment by repeatedly** [comment]
Awesome work!

**Comment by okkez** [comment]
Thanks!

**Pull request merged**
