### PR TITLE
Fix concetion pool & timeout (issues #82)

### PR DESCRIPTION
**Pull request by zamanimehdi**
ref: https://github.com/fluent/fluent-plugin-sql/issues/82

### CODE REVIEW

**Comment by ganmacs** [comment]
Commits about #80 are included.

**Comment by repeatedly** [comment]
`pool` and `timeout` default values are same with ActiveRecord?

**Comment by zamanimehdi** [comment]
> `pool` and `timeout` default values are same with ActiveRecord?

In non-parallel applications, requests sent via activerecord do not require a large amount of parallel request and connection pool, while in fluentd parallel transmissions , the amount of connection pool must be able to cover the number of simultaneous requests.
Therefore,  activerecord connection pools must be greater than parallel fluentd threads.
On the other hand, according to bulk-insert, the value of timeout should be more than the usual requests. 
The default values are set based on my own experience of working with fluentd.

**Comment by repeatedly** [comment]
Thanks. This patch will be included v2.0.0.

**Pull request merged**
