### PR TITLE
Remove unused .travis.yml

### PR DESCRIPTION
**Pull request by kenhys**
The dependency to Travis CI was already removed by #98

### CODE REVIEW

**Comment by cosmo0920** [comment]
Also we should disable to run CI tasks in Travis CI settings: https://travis-ci.org/github/fluent/fluent-plugin-sql.

**Comment by ashie** [comment]
Testing on ruby-head (and 3.0) is missing on GitHub Actions.
Hmm, it seems that it has Ruby 3.0's keyword arguments issue: https://travis-ci.org/github/fluent/fluent-plugin-sql/jobs/761417606

**Comment by cosmo0920** [comment]
I'm not sure why fluent-plugin-sql still uses activerecord 5.2.5, but activerecord 6.1.3.1 will solve dropping Ruby 3.0's keywords arguments interoperability issue:

```log
$ rbenv versions
  system
  2.1.8
  2.3.8
  2.4.1
  2.4.9
  2.5.1
  2.5.8
  2.6.0
  2.6.1
  2.6.3
  2.6.5
  2.6.6
  2.7.0
  2.7.1
  2.7.2
  2.8.0-dev
  3.0.0
* 3.0.1 (set by /Users/cosmo/GitHub/fluent-plugin-sql/.ruby-version)
  jruby-9.1.12.0
  jruby-9.2.11.0
  jruby-9.2.13.0
```
```console
$ % bundle exec rake test

/Users/cosmo/.rbenv/versions/3.0.1/bin/ruby -w -I"lib:lib:test" /Users/cosmo/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/fixtures/schema.rb" "test/plugin/test_in_sql.rb" "test/plugin/test_in_sql_with_custom_time.rb" "test/plugin/test_out_sql.rb" 
-- create_table("logs", {:force=>:cascade})
   -> 0.6878s
-- create_table("messages", {:force=>:cascade})
   -> 0.0105s
-- create_table("messages_custom_time", {:force=>:cascade})
   -> 0.0127s
/Users/cosmo/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fluentd-1.12.2/lib/fluent/config/literal_parser.rb:194: warning: assigned but unused variable - e
/Users/cosmo/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fluentd-1.12.2/lib/fluent/plugin/parser_syslog.rb:487: warning: assigned but unused variable - e
-- create_table("logs", {:force=>:cascade})
   -> 0.0311s
-- create_table("messages", {:force=>:cascade})
   -> 0.0558s
-- create_table("messages_custom_time", {:force=>:cascade})
   -> 0.0077s
Loaded suite /Users/cosmo/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/rake_test_loader
Started
........
Finished in 12.531567 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
8 tests, 22 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
0.64 tests/s, 1.76 assertions/s
```

**Comment by ashie** [comment]
We should upgrade activesuport & activerecord to 6.1 so that #87 will be also resolved.

**Comment by cosmo0920** [comment]
> We should upgrade activesuport & activerecord to 6.1 so that #87 will be also resolved (no need to downgrade tzinfo manually anymore).

This can be fixed in https://github.com/fluent/fluent-plugin-sql/pull/101.

**Comment by ashie** [comment]
I've also deactivate the webhook for travis-ci.

**Pull request merged**
