### PR TITLE
Add missing require for Fluentd v0.14

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by repeatedly** [comment]
Thx!

**Comment by pavgup** [comment]
Happened to run into this issue `[error]: unexpected error error="uninitialized constant Fluent::Input"` and realized it was a missing require statement.  So, I started manually editing the plugin to fix things, and then realized you all had made the fix to this already.  Yay!  But could this plugin be re-released as a new version with this require statement included?

**Comment by repeatedly** [comment]
@pavgup Release v0.5.2. Try it!

**Comment by pavgup** [comment]
Woot.  You are a rockstar, @repeatedly!   Thanks dude.  Changes pulled!

**Pull request merged**
