### PR TITLE
Organize travis.yml

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by repeatedly** [comment]
Tests failed...

**Comment by cosmo0920** [comment]
I'm investigating what causes test failure, but I don't find a solution for now. :cry:

**Comment by cosmo0920** [comment]
I've found that above test failure to caused by pg gem `v1.0.0`.
Currently, I specify to install pg gem v0.21.0 in this PR.

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
