### PR TITLE
Add inject section to example configuration

### PR DESCRIPTION
**Pull request by dobesv**
To help others avoid the confusion I had when the timestamp property was not available for insertion.

### CODE REVIEW

**Comment by dobesv** [comment]
See https://github.com/fluent/fluent-plugin-sql/issues/92 for fix.

**Review by cosmo0920 — APPROVED** [review]

**Comment by cosmo0920** [comment]
@ashie Could you kindly take a look on this?
This PR seems to be useful for adding timestamp usecases.

**Review by ashie — CHANGES_REQUESTED** [review]
An example output of this config is like this: `2021-03-05T00:46:01%.000000000:z`
I'm not sure but is it a generic format?
If not, using same format with https://docs.fluentd.org/configuration/inject-section#example is better.

**Comment by kenhys** [comment]
@dobesv could you take a look at it again?

**Comment by dobesv** [comment]
Sorry I'm not using this plugin any more and I don't remember how to use it or test it.

**Pull request closed without merging**
